export const products = [
  {
    id: 1,
    title: "Paleta Gold",
    price: 140000,
    stock: 5,
    description: "Paleta 100% de ataque",
    category: "paletas",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762495/conqueror-gold_xli2u1.png",
  },
  {
    id: 2,
    title: "Paleta Seal",
    price: 120000,
    stock: 5,
    description: "Paleta Hibrida, calidad y precio",
    category: "paletas",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762497/kings-seal_ctzd6e.png",
  },
  {
    id: 3,
    title: "Paleta Tear",
    price: 110000,
    stock: 5,
    description: "Nuestra paleta revolucionaria, para los distintos",
    category: "paletas",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762497/golden-tear_rjmgvc.png",
  },
  {
    id: 4,
    title: "Paleta Heir",
    price: 100000,
    stock: 5,
    description: "La mejor paleta de principiantes del TODO el mercado",
    category: "paletas",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762493/the-heir_qzkoro.png",
  },
  {
    id: 5,
    title: "Zapatilla Court",
    price: 42000,
    stock: 5,
    description: "Las mejores zapatillas para el Padel",
    category: "zapatillas",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762492/conqueror-court_pg9aux.png",
  },
  {
    id: 6,
    title: "Zapatilla Hybrid",
    price: 42000,
    stock: 5,
    description: "Las zapatillas hibridas para padel, cesped o cemento",
    category: "zapatillas",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762495/conqueror-hybrid_dwtmut.png",
  },
  {
    id: 7,
    title: "Zapatilla Clinical",
    price: 45000,
    stock: 5,
    description:
      "Las zapatillas para deportistas con lesiones cronicas de tobillo o rodilla",
    category: "zapatillas",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762492/ruler-clinical_y33c8x.png",
  },
  {
    id: 8,
    title: "Zapatilla Running",
    price: 32000,
    stock: 5,
    description: "Las zapatillas para deporte diario, gym o running",
    category: "zapatillas",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762492/royal-running_ot1wj4.png",
  },
  {
    id: 9,
    title: "Remeras Combo Legacy",
    price: 30000,
    stock: 5,
    description:
      "Las remeras con tecnologias de ultima generacion, para maxima comodidad",
    category: "remeras",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762493/combo-legacy_gpmkcl.png",
  },
  {
    id: 10,
    title: "Remeras Duo Conqueror",
    price: 22000,
    stock: 5,
    description: "Nuestro par de remeras, para aquello que juegan juntos",
    category: "remeras",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762495/conquerors_vr4ubp.png",
  },
  {
    id: 11,
    title: "Remera Tunic",
    price: 14000,
    stock: 5,
    description: "Nuestra Remera 100% personalizable, para jugadores Pros",
    category: "remeras",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762497/fusion-tunic_zt4dse.png",
  },
  {
    id: 12,
    title: "Remeras Duo Conqueror",
    price: 10000,
    stock: 5,
    description: "Nuestra remera para todos los amantes del Padel",
    category: "remeras",
    img: "https://res.cloudinary.com/dyshyq2vl/image/upload/v1677762492/royal-suit_mtuda9.png",
  },
];
